// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreasureHuntApi.Models;

#nullable disable

namespace TreasureHuntApi.Migrations
{
    [DbContext(typeof(TreasureHuntContext))]
    partial class TreasureHuntContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("TreasureHuntApi.Models.TreasureHuntInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("M")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Matrix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("N")
                        .HasColumnType("INTEGER");

                    b.Property<int>("P")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Inputs");
                });

            modelBuilder.Entity("TreasureHuntApi.Models.TreasureHuntResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinFuel")
                        .HasColumnType("REAL");

                    b.Property<string>("Path")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
